services:
  coqui-tts:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: coqui-xtts
    restart: unless-stopped

    ports:
      - "5002:5002"

    volumes:
      - tts_models:/root/.local/share/tts
      - ./samples:/samples
      - ./app.py:/app/app.py:ro
      - ./static:/app/static:ro

    environment:
      - COQUI_TOS_AGREED=1
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128
      - PYTHONWARNINGS=ignore::FutureWarning

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    command: ["/opt/venv/bin/uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5002"]

    shm_size: "2g"

volumes:
  tts_models:
